FROM davarski/spark301-k8s-minio-dl:latest

USER root 

# Install Spylon Kernel (Scala and JVM)
run pip3 install spylon-kernel \
  && python3 -m spylon_kernel install --sys-prefix

# Install Maven (provides for auto package fetch in Spark 3)
RUN apt-get install -y maven

# Install dotnet core and .NET Interactive
RUN wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb \
  && dpkg -i packages-microsoft-prod.deb \
  && apt-get update \
  && apt-get install -y dotnet-sdk-3.1 \
  && dotnet tool install -g --add-source "https://dotnet.myget.org/F/dotnet-try/api/v3/index.json" Microsoft.dotnet-interactive

# Install IRKernel in R
RUN echo "install.packages('devtools'); devtools::install_github('IRkernel/IRkernel'); IRkernel::installspec(user=FALSE);" | R --no-save

# Install jupyter-server-proxy
RUN pip3 install jupyter-server-proxy \
  && jupyter serverextension enable --sys-prefix jupyter_server_proxy

# Install S3 contents viewer
RUN jupyter labextension install jupyterlab-s3-browser \
  && pip install jupyterlab-s3-browser \
  && jupyter serverextension enable --py jupyterlab_s3_browser 

# Install GNU Octave and Associated Kernel
RUN apt-get install -y octave octave-splines octave-image octave-doc octave-database \
    octave-control octave-communications octave-data-smoothing octave-dataframe \
    octave-dicom octave-fpl octave-geometry octave-image-acquisition octave-io octave-msh \
    octave-nan octave-plplot octave-signal octave-stk octave-strings octave-symbolic \
    octave-tsa octave-video  \
  && pip3 install octave_kernel

# Install Spark Magic
RUN apt-get install -y libkrb5-dev \
  && pip3 install sparkmagic \
  && jupyter nbextension enable --py --sys-prefix widgetsnbextension \
  && jupyter labextension install "@jupyter-widgets/jupyterlab-manager" \
  && jupyter serverextension enable --py sparkmagic

# Set User back to jovyan/1000
USER 1000

# Activate .NET interactive for jovyan user
RUN dotnet tool install -g --add-source "https://dotnet.myget.org/F/dotnet-try/api/v3/index.json" Microsoft.dotnet-interactive \
  && /home/jovyan/.dotnet/tools/dotnet-interactive jupyter install
ENV DOTNET_CLI_TELEMETRY_OPTOUT=1

# Set active path in the notebook instance
ENV PATH="/home/jovyan/.dotnet/tools:/opt/maven/bin:${PATH}"


